language: python
python:
  - "3.6"

notifications:
  email:
    recipients:
      - renkeju@gmail.com
    on_success: change
    on_failure: always

install:
  - pip install -r requirements.txt

script:
  - sphinx-build -nW -b html -d build/doctrees . build/html

after_script:
  - cd build/html
  - git init
  - git remote add origin https://${REF}
  - git add .
  - git commit -m "Updated By Travis-CI With Build $TRAVIS_BUILD_NUMBER For Github Pages"
  - git push --force --quiet "https://${TOKEN}@${REF}" master:gh-pages

branches:
  only:
    - master

env:
  global:
    - REF=github.com/renkeju/sphinx-template.git
